services:
  mysql:
    image: mysql:8.0
    container_name: mysql-estudiantes
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: registro_estudiantes
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      TZ: America/Bogota

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

    networks:
      - estudiantes_net

    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:

networks:
  estudiantes_net:
    driver: bridge
